# Generated by Django 4.2.4 on 2023-09-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRecords',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('employee_salary', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Employee Record',
                'verbose_name_plural': 'Employee Records',
            },
        ),
        migrations.CreateModel(
            name='EmployeePreviousExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_company_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeerecords')),
            ],
            options={
                'verbose_name': 'Employee Previous Experience',
                'verbose_name_plural': 'Employee Previous Experience',
            },
        ),
    ]
