# Generated by Django 4.2.4 on 2023-09-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('standard', models.IntegerField()),
                ('fathers_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('parent_contact_number', models.BigIntegerField()),
                ('profile_image', models.ImageField(blank=True, upload_to='image/profile')),
            ],
        ),
    ]
